external_components:
  - source:
      type: git
      url: https://github.com/Lafayette2958/esphome-gasboard7500opc
    components: [gasboard7500opc]

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

sensor:
  - platform: gasboard7500opc
    id: gas_sensor
    gas_flow:
      name: "Gas Flow"
      unit_of_measurement: "L/min"
      accuracy_decimals: 2
    gas_temperature:
      name: "Gas Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1   
